version: '3.1'
services:
  web:
    image: odoo:12.0
    container_name: odoo12
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - web-data:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./addons:/mnt/addons
      - ./addons/enterprise-12.0:/mnt/addons-enterprise
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
  db:
    image: postgres:15
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    restart: always
volumes:
  web-data:
